// Enhanced Question Database with 100+ thoughtful questions per category
const questions = {
    // Round 2: Getting to Know You - First date vibes, lighter but meaningful
    'first-date': [
      // Dreams & Aspirations (20 questions)
      "What's a dream you've had since childhood that you still think about?",
      "If you could master any skill overnight, what would it be and why?",
      "What's one adventure you want to have in the next year?",
      "If money wasn't a factor, what would you do with your time?",
      "What's a goal you're actively working toward right now?",
      "What accomplishment are you most proud of from the last year?",
      "If you could live anywhere in the world for a year, where would it be?",
      "What's something you want to learn but haven't started yet?",
      "What does your perfect day look like from start to finish?",
      "If you could have dinner with anyone living or dead, who would it be?",
      "What's a risk you want to take but haven't yet?",
      "What would you do if you knew you couldn't fail?",
      "What's one thing you want to be remembered for?",
      "If you could change one thing about the world, what would it be?",
      "What's your biggest dream that you haven't told many people?",
      "What age do you feel like inside and why?",
      "If you could relive one year of your life, which would it be?",
      "What's something you've always wanted to try but haven't?",
      "What would your dream home look like?",
      "If you won the lottery tomorrow, what's the first thing you'd do?",
  
      // Personal Stories (20 questions)
      "What's the best advice you've ever received?",
      "Tell me about a time you surprised yourself.",
      "What's a tradition from your childhood you want to continue?",
      "What's the most spontaneous thing you've ever done?",
      "Tell me about a teacher or mentor who changed your life.",
      "What's a mistake that turned out to be a blessing?",
      "What's the bravest thing you've ever done?",
      "Tell me about your first best friend.",
      "What's a compliment you received that stuck with you?",
      "What's the best gift you've ever received and why?",
      "Tell me about a time you stood up for something you believed in.",
      "What's a small moment from your past that had a big impact?",
      "What's the kindest thing someone has done for you?",
      "Tell me about a time you felt truly understood.",
      "What's a childhood memory that makes you smile?",
      "What's the most important lesson you learned from a past relationship?",
      "Tell me about a time you felt really proud of someone else.",
      "What's a fear you've overcome?",
      "What's the best trip you've ever taken?",
      "Tell me about a moment when you felt completely at peace.",
  
      // Values & Beliefs (20 questions)
      "What values are most important to you in life?",
      "What does success mean to you?",
      "How do you define a life well-lived?",
      "What role does spirituality or faith play in your life?",
      "What's a cause you're passionate about?",
      "What does friendship mean to you?",
      "How important is family to you?",
      "What's your philosophy on work-life balance?",
      "What do you think happens after we die?",
      "How do you handle disagreements with people you care about?",
      "What's more important: being right or being kind?",
      "How do you define love?",
      "What's your biggest priority in life right now?",
      "What injustice in the world bothers you most?",
      "How do you make important decisions?",
      "What role does money play in your happiness?",
      "What's your definition of home?",
      "How important is personal growth to you?",
      "What legacy do you want to leave?",
      "What brings you the most joy in life?",
  
      // Fun & Lighthearted (20 questions)
      "What's your most unusual talent or party trick?",
      "What's the weirdest food combination you actually enjoy?",
      "If you could have any superpower for a day, what would you choose?",
      "What's your go-to karaoke song?",
      "What fictional character do you relate to most?",
      "What's the most embarrassing song you love?",
      "If your life was a movie, what would it be called?",
      "What's the strangest dream you remember having?",
      "What's your most irrational fear?",
      "If you could be any animal for a day, what would you be?",
      "What's the worst fashion trend you participated in?",
      "What's your guilty pleasure TV show or movie?",
      "If you had to eat one meal for the rest of your life, what would it be?",
      "What's the most ridiculous thing on your bucket list?",
      "What conspiracy theory do you secretly hope is true?",
      "What's the weirdest compliment you've ever received?",
      "If you could rename yourself, what name would you choose?",
      "What's the most useless skill you have?",
      "What's your most controversial food opinion?",
      "If you could live in any TV show universe, which would it be?",
  
      // Preferences & Opinions (20 questions)
      "Are you more of a morning person or night owl?",
      "Do you prefer planning everything or being spontaneous?",
      "Beach vacation or mountain adventure?",
      "Would you rather be too hot or too cold?",
      "Big party or intimate gathering?",
      "Do you prefer giving gifts or receiving them?",
      "City life or country living?",
      "Would you rather have more time or more money?",
      "Do you prefer cooking or being cooked for?",
      "Books or movies?",
      "Would you rather be able to fly or be invisible?",
      "Do you prefer texting or phone calls?",
      "Sweet or savory?",
      "Would you rather travel to the past or the future?",
      "Do you prefer summer or winter?",
      "Dogs or cats?",
      "Would you rather be famous or rich?",
      "Do you prefer routine or variety?",
      "Indoor or outdoor activities?",
      "Would you rather lose your phone or your wallet?",
  
      // Creative & Imaginative (20 questions)
      "If you could design your perfect weekend, what would it include?",
      "What would your superhero name and power be?",
      "If you wrote a book, what would it be about?",
      "Design your perfect pizza - what's on it?",
      "If you could create a new holiday, what would it celebrate?",
      "What would your dream job look like?",
      "If you could add one rule to any sport, what would it be?",
      "What would you name your boat if you had one?",
      "If you could open any kind of business, what would it be?",
      "What would your campaign slogan be if you ran for president?",
      "If you could invent something, what would it be?",
      "What would your DJ name be?",
      "If you could create a new ice cream flavor, what would it be?",
      "What would your warning label say?",
      "If you could start a band, what would you name it?",
      "What would your autobiography be titled?",
      "If you could design a theme park ride, what would it be like?",
      "What would your personal mascot be?",
      "If you could create a new emoji, what would it be?",
      "What would your time machine look like?"
    ],
  
    // Round 4: Going Deeper - Building connection and understanding
    'getting-closer': [
      // Emotional Intelligence (20 questions)
      "How do you typically process difficult emotions?",
      "What emotion do you have the hardest time expressing?",
      "How do you know when you're truly happy?",
      "What triggers make you feel most vulnerable?",
      "How do you show love to the people closest to you?",
      "What helps you feel emotionally safe with someone?",
      "How do you handle disappointment?",
      "What makes you feel most understood?",
      "How do you deal with jealousy when it comes up?",
      "What emotion do you wish you could feel more often?",
      "How do you comfort yourself when you're sad?",
      "What makes you feel most alive and energized?",
      "How do you know when to ask for help?",
      "What emotion are you most comfortable showing others?",
      "How do you handle feeling overwhelmed?",
      "What makes you feel most grateful?",
      "How do you express anger in healthy ways?",
      "What helps you feel centered and grounded?",
      "How do you celebrate your wins?",
      "What emotion do you struggle to understand in others?",
  
      // Relationships & Connection (20 questions)
      "What does a healthy relationship look like to you?",
      "How do you maintain friendships over time?",
      "What patterns from past relationships are you working to change?",
      "How do you know when you can trust someone?",
      "What boundaries are most important to you?",
      "How do you handle conflict in close relationships?",
      "What makes you feel most connected to someone?",
      "How do you show up for people when they need you?",
      "What relationship in your life has taught you the most?",
      "How do you maintain your identity in relationships?",
      "What makes you feel secure in a relationship?",
      "How do you navigate differences with people you love?",
      "What role does forgiveness play in your relationships?",
      "How do you know when a relationship isn't serving you?",
      "What do you need most from a romantic partner?",
      "How do you balance independence and togetherness?",
      "What relationship advice would you give your younger self?",
      "How do you keep romance alive over time?",
      "What makes a relationship feel like home to you?",
      "How do you handle jealousy in relationships?",
  
      // Personal Growth (20 questions)
      "What aspect of yourself are you actively working to improve?",
      "How have you changed most in the last five years?",
      "What habit would you most like to develop?",
      "What limiting belief are you trying to overcome?",
      "How do you push yourself out of your comfort zone?",
      "What failure taught you the most?",
      "How do you measure personal growth?",
      "What shadow aspect of yourself are you learning to accept?",
      "How do you stay motivated when things get difficult?",
      "What part of your personality do you wish you could change?",
      "How do you practice self-compassion?",
      "What's the bravest thing you've done for your growth?",
      "How do you handle criticism constructively?",
      "What old version of yourself are you most proud of outgrowing?",
      "How do you stay true to yourself when others disagree?",
      "What personal breakthrough changed your life?",
      "How do you balance self-improvement with self-acceptance?",
      "What teacher appeared in your life at the perfect time?",
      "How do you know when you're on the right path?",
      "What would you tell your past self about growth?",
  
      // Family & Background (20 questions)
      "How has your family shaped who you are today?",
      "What family tradition do you want to continue or start?",
      "How would you describe your relationship with your parents?",
      "What role do you play in your family dynamic?",
      "How has your birth order affected your personality?",
      "What family patterns are you working to break?",
      "What's the best thing your family taught you?",
      "How do you handle family conflicts?",
      "What aspects of your upbringing are you grateful for?",
      "How has your cultural background influenced you?",
      "What family member do you most take after?",
      "How do you maintain boundaries with family?",
      "What family story gets told over and over?",
      "How has your definition of family evolved?",
      "What would you do differently as a parent?",
      "How do you honor your roots while growing beyond them?",
      "What family wound are you working to heal?",
      "How important is chosen family to you?",
      "What legacy from your family do you want to pass on?",
      "How do you navigate different values within your family?",
  
      // Life Philosophy (20 questions)
      "What life lesson took you the longest to learn?",
      "How do you find meaning in difficult times?",
      "What truth about life do you wish you'd known sooner?",
      "How do you decide what's worth your energy?",
      "What philosophy guides your daily decisions?",
      "How do you define a life well-lived?",
      "What paradox about life fascinates you?",
      "How do you find balance between planning and flowing?",
      "What belief system gives you comfort?",
      "How do you make peace with uncertainty?",
      "What wisdom would you pass to future generations?",
      "How do you determine your priorities?",
      "What questions about life keep you up at night?",
      "How do you find joy in simple moments?",
      "What illusion did you have to let go of?",
      "How do you cultivate gratitude?",
      "What truth do you hold even when it's unpopular?",
      "How do you handle life's unfairness?",
      "What gives your life the most meaning?",
      "How do you stay hopeful in dark times?",
  
      // Vulnerability & Trust (20 questions)
      "What makes you feel safe enough to be vulnerable?",
      "When was the last time you cried and why?",
      "What secret fear holds you back sometimes?",
      "How do you ask for what you need?",
      "What part of yourself do you hide from most people?",
      "When do you feel most exposed or raw?",
      "How do you handle feeling misunderstood?",
      "What would you be afraid to lose?",
      "When was the last time you felt truly seen?",
      "What do you need to hear when you're struggling?",
      "How do you let people in when it's scary?",
      "What wall are you still working on bringing down?",
      "When do you feel safest to be yourself?",
      "What shame are you working to release?",
      "How do you trust again after being hurt?",
      "What would you want someone to know about your pain?",
      "When do you feel most authentic?",
      "How do you show others your true self?",
      "What healing are you still working through?",
      "What would help you feel more understood?"
    ],
  
    // Round 6 Option A: Soul Connection - Deep spiritual and emotional intimacy
    'long-term': [
      // Soul & Purpose (25 questions)
      "What do you believe your soul came here to learn?",
      "How do you connect with something greater than yourself?",
      "What experiences have made you believe in magic or miracles?",
      "When do you feel most aligned with your purpose?",
      "What calling have you been avoiding?",
      "How do you nurture your spiritual side?",
      "What synchronicities have guided your path?",
      "When do you feel most connected to the universe?",
      "What spiritual practice grounds you?",
      "How has your spiritual journey evolved?",
      "What divine timing have you witnessed in your life?",
      "When do you feel most in flow with life?",
      "What soul lesson keeps repeating in your life?",
      "How do you tap into your intuition?",
      "What spiritual awakening have you experienced?",
      "When do you feel most connected to your higher self?",
      "What sacred practice do you want to develop?",
      "How do you honor the divine within you?",
      "What spiritual truth resonates deepest with you?",
      "When have you felt the presence of something greater?",
      "What soul contract do you feel you have?",
      "How do you cultivate inner peace?",
      "What spiritual teacher has impacted you most?",
      "When do you feel most expansive?",
      "What practice helps you remember who you really are?",
  
      // Deep Love & Connection (25 questions)
      "How has your capacity to love evolved over time?",
      "What walls around your heart are you ready to dissolve?",
      "When have you felt love as a transformative force?",
      "How do you stay open when love feels risky?",
      "What does unconditional love mean to you?",
      "How do you love someone through their shadows?",
      "When have you chosen love over fear?",
      "What aspect of love still mystifies you?",
      "How do you maintain passion in long-term connection?",
      "What does soul-level intimacy feel like to you?",
      "How do you honor both togetherness and autonomy?",
      "When do you feel most cherished?",
      "What love story inspires you?",
      "How do you keep choosing each other daily?",
      "What does forever mean to you?",
      "How do you love without losing yourself?",
      "When has love asked you to grow?",
      "What sacred space do you create together?",
      "How do you navigate the seasons of relationship?",
      "What vow would you make to love itself?",
      "How has love healed you?",
      "What does your heart know that your mind doesn't?",
      "How do you trust love when it's been broken before?",
      "What would you sacrifice for true love?",
      "How do you keep your heart soft in a hard world?",
  
      // Healing & Transformation (25 questions)
      "What wound is ready to become wisdom?",
      "How are you different from who you were five years ago?",
      "What shadow aspect are you integrating?",
      "When did you realize you had the power to heal yourself?",
      "What generational pattern ends with you?",
      "How do you alchemize pain into purpose?",
      "What part of your story are you rewriting?",
      "When did you stop abandoning yourself?",
      "What healing journey are you currently on?",
      "How do you make friends with your darkness?",
      "What trigger has become a teacher?",
      "When did you realize your sensitivity was a strength?",
      "What are you ready to forgive?",
      "How do you honor your healing process?",
      "What transformation are you in the middle of?",
      "When did you reclaim your power?",
      "What medicine do you offer the world?",
      "How do you stay soft while building boundaries?",
      "What Phoenix moment have you experienced?",
      "When did you choose yourself?",
      "What aspect of healing surprised you?",
      "How do you hold space for your own evolution?",
      "What would you tell someone starting their healing journey?",
      "When did pain become your portal?",
      "How has healing changed your capacity to love?",
  
      // Dreams & Visions (25 questions)
      "What future are you actively creating?",
      "What dream feels too big to speak aloud?",
      "How do you want to be remembered?",
      "What legacy will your love leave?",
      "What world do you want to create together?",
      "How do you nurture shared dreams?",
      "What vision keeps pulling you forward?",
      "What would you create if you knew you couldn't fail?",
      "How do you want to grow old together?",
      "What adventure is your soul craving?",
      "What impact do you want your life to have?",
      "How do you dream bigger together than apart?",
      "What future self are you becoming?",
      "What possibility excites and scares you?",
      "How do you hold space for each other's evolution?",
      "What dream have you been afraid to pursue?",
      "What would you do with unlimited resources?",
      "How do you want to change the world?",
      "What seeds are you planting for the future?",
      "What vision of love do you want to model?",
      "How do you stay connected to possibility?",
      "What dreams have you outgrown?",
      "What calling won't leave you alone?",
      "How do you co-create your reality?",
      "What future are you grateful for in advance?"
    ],
  
    // Round 6 Option B: Heating Up - Passion, desire, and intimate connection
    'spicy': [
      // Desire & Attraction (25 questions)
      "What first attracted you to me that you haven't told me?",
      "When do you find me most irresistible?",
      "What subtle thing do I do that turns you on?",
      "How has your attraction to me evolved over time?",
      "What outfit of mine drives you wild?",
      "When did you first know you wanted me?",
      "What feature of mine do you find yourself staring at?",
      "How do you like to build anticipation?",
      "What tone of voice do I use that affects you?",
      "When do you feel most desired by me?",
      "What non-physical quality of mine turns you on?",
      "How do you like to be seduced?",
      "What memory of us still makes you hot?",
      "When do you feel most attracted to me?",
      "What would you want to do if we had a hotel room for 24 hours?",
      "How do you like to be teased?",
      "What kiss of ours do you replay in your mind?",
      "When did you last fantasize about me?",
      "What boundary would you like to push together?",
      "How has our chemistry surprised you?",
      "What energy between us is most electric?",
      "When do you feel most connected to my body?",
      "What unspoken desire do you have?",
      "How do you want to be wanted?",
      "What would you do to me if there were no limits?",
  
      // Intimacy & Vulnerability (25 questions)
      "What makes you feel most intimate beyond physical touch?",
      "How do you like to be touched when you're emotional?",
      "What kind of intimacy do you crave more of?",
      "When do you feel most bare and vulnerable with me?",
      "What walls do you still have up in our physical connection?",
      "How does emotional intimacy affect physical desire for you?",
      "What intimate moment between us felt most sacred?",
      "When do you feel safest to express desire?",
      "What vulnerability during intimacy scared but freed you?",
      "How do you want to be held?",
      "What intimate ritual would you like to create together?",
      "When do our souls feel most intertwined?",
      "What tender moment between us changed you?",
      "How do you express need without words?",
      "What intimate fear are you ready to release?",
      "When does time stop for you with me?",
      "What touch heals something in you?",
      "How can I make you feel more cherished?",
      "What intimate moment do you want to recreate?",
      "When do you feel most accepted by me?",
      "What does making love mean to you versus having sex?",
      "How has our intimacy healed you?",
      "What intimate growth edge are you on?",
      "When do you feel most powerful in your body?",
      "What intimate connection do you want to deepen?",
  
      // Fantasy & Exploration (25 questions)
      "What fantasy have you been curious about?",
      "Where would you want to make love that we haven't?",
      "What roleplay scenario intrigues you?",
      "How adventurous do you want to be together?",
      "What boundary are you curious about exploring?",
      "What scene from a movie awakened something in you?",
      "How do you want to surprise me intimately?",
      "What sensory experience do you want to explore?",
      "What intimate game would you want to play?",
      "How would you want to seduce me all over again?",
      "What fantasy feels too wild to share?",
      "What experience would you want to have in nature?",
      "How do you want to explore power dynamics?",
      "What would you want to do with no time constraints?",
      "What intimate adventure is on your bucket list?",
      "How do you want to play with anticipation?",
      "What fantasy have you outgrown?",
      "What new side of yourself do you want to explore?",
      "How do you want to break routine together?",
      "What intimate creativity wants to emerge?",
      "What scenario would make you feel most free?",
      "How do you want to explore each other's bodies differently?",
      "What intimate challenge would you want to try?",
      "What fantasy would deepen our connection?",
      "How do you want to keep discovering each other?",
  
      // Passion & Energy (25 questions)
      "When does passion overtake your whole body?",
      "How do you channel sexual energy creatively?",
      "What ignites your fire when it's dimmed?",
      "When do you feel most alive in your sexuality?",
      "How do you want our passion to evolve?",
      "What makes you feel like a sexual being beyond sex?",
      "When does desire consume your thoughts?",
      "How do you cultivate passion in daily life?",
      "What awakens your primal energy?",
      "When do you feel most magnetically powerful?",
      "How does passion show up outside the bedroom?",
      "What makes you feel most embodied?",
      "When does our energy create sparks?",
      "How do you want to channel our chemistry?",
      "What passion have you been suppressing?",
      "When do you feel most uninhibited?",
      "How do you keep passion alive long-term?",
      "What energy exchange do you crave?",
      "When does desire feel spiritual to you?",
      "How do you honor your sexual energy?",
      "What makes you feel most erotically alive?",
      "When does passion feel like worship?",
      "How do you want to celebrate our desire?",
      "What fire between us needs more fuel?",
      "When do you feel most sexually confident?"
    ],

    // NEW CATEGORIES for winner-chooses-question flow
    
    // Round 1 Categories (Lighter) - after Guessing Game
    'personal-preferences': [
        "What's your favorite season and why?",
        "What's your ideal way to spend a Sunday morning?", 
        "What's your go-to comfort food when you're stressed?",
        "What's your favorite way to relax after a long day?",
        "What's your preferred way to stay active (or not)?",
        "What's your favorite type of weather?",
        "What's your ideal vacation style - adventure or relaxation?",
        "What's your favorite time of day and why?",
        "What's your go-to outfit style when you want to feel confident?",
        "What's your favorite way to celebrate good news?",
        "What's your preferred way to spend money on yourself?",
        "What's your ideal work environment?",
        "What's your favorite type of music for different moods?",
        "What's your preferred sleeping setup (pillows, temperature, etc)?",
        "What's your favorite holiday tradition?",
        "What's your ideal date night activity?",
        "What's your preferred communication style when upset?",
        "What's your favorite way to show affection?",
        "What's your ideal morning routine?",
        "What's your favorite simple pleasure in life?"
    ],
    
    'fun-personality': [
        "What's your most unusual talent or party trick?",
        "What's the weirdest food combination you actually enjoy?",
        "What's your most irrational fear?",
        "What's your guilty pleasure TV show or movie?", 
        "What conspiracy theory do you secretly hope is true?",
        "What's the most embarrassing song you love?",
        "What's your weirdest habit that you don't think others know about?",
        "What's the strangest dream you remember having?",
        "What's your most controversial food opinion?",
        "What would your warning label say?",
        "What's your secret superpower in social situations?",
        "What's the most random fact you know?",
        "What's your weirdest childhood belief?",
        "What's your most unpopular opinion about movies/TV?",
        "What's your strangest pet peeve?",
        "What would you do if you were invisible for a day?",
        "What's your most embarrassing autocorrect fail?",
        "What's the weirdest compliment you've ever received?",
        "What's your most irrational competitive streak?",
        "What fictional character do you relate to most and why?"
    ],
    
    'background-stories': [
        "What's the best advice you've ever received and who gave it to you?",
        "Tell me about a time you surprised yourself with your own courage.",
        "What's a tradition from your childhood you want to continue?",
        "What's the most spontaneous thing you've ever done?",
        "Tell me about your first best friend - what made them special?",
        "What's a moment that completely changed your perspective on life?",
        "What's the kindest thing a stranger has ever done for you?",
        "What's a mistake that turned out to be a blessing in disguise?",
        "What's the bravest thing you've ever done for love?",
        "What's a compliment you received that you'll never forget?",
        "Tell me about a teacher who made a real difference in your life.",
        "What's your most cherished childhood memory?",
        "What's a time you stood up for something you believed in?",
        "What's the most important lesson you learned from failure?",
        "Tell me about a moment when you felt truly proud of yourself.",
        "What's a family story that always makes you laugh?",
        "What's the most meaningful gift you've ever received?",
        "Tell me about a time you felt completely understood by someone.",
        "What's a fear you've successfully overcome?",
        "What's your favorite memory of feeling completely carefree?"
    ],
    
    // Round 2 Categories (Medium) - after Trivia  
    'values-beliefs': [
        "What values are absolutely non-negotiable for you in life?",
        "What does success truly mean to you beyond money or status?",
        "How do you define a life well-lived?",
        "What role does spirituality or faith play in your daily life?",
        "What cause or injustice do you feel most passionate about?",
        "How do you decide what's worth your time and energy?",
        "What's your philosophy on forgiveness?",
        "How important is honesty vs. kindness when they conflict?",
        "What do you believe happens after we die?",
        "How do you find meaning during difficult times?",
        "What's your biggest priority in life right now?",
        "How do you define true friendship?",
        "What role should money play in major life decisions?",
        "How do you handle moral dilemmas?",
        "What legacy do you want to leave behind?",
        "What's your philosophy on work-life balance?",
        "How important is personal growth vs. stability to you?",
        "What do you believe about destiny vs. free will?",
        "How do you determine right from wrong?",
        "What brings you the deepest sense of joy and fulfillment?"
    ],
    
    'relationships-love': [
        "What does a truly healthy relationship look like to you?",
        "How do you prefer to show love to people you care about?",
        "What makes you feel most connected and understood by someone?",
        "How do you handle conflict in close relationships?",
        "What do you need most from a romantic partner to feel secure?",
        "How do you maintain your sense of self in relationships?",
        "What are your most important boundaries in relationships?",
        "How do you know when you can truly trust someone?",
        "What relationship pattern are you working to change?",
        "How do you keep romance and passion alive long-term?",
        "What's your biggest fear about love and relationships?",
        "How do you balance independence with partnership?",
        "What's the most important thing you've learned about love?",
        "How do you handle jealousy when it comes up?",
        "What does emotional intimacy mean to you?",
        "How do you want to grow together as a couple?",
        "What makes a relationship feel like 'home' to you?",
        "How do you support a partner through difficult times?",
        "What's your definition of unconditional love?",
        "How has your understanding of love evolved over time?"
    ],
    
    'dreams-goals': [
        "What's a dream you've carried since childhood that still excites you?",
        "If money wasn't a factor, how would you spend your time?",
        "What's one adventure you absolutely want to have in the next year?",
        "What accomplishment from this past year are you most proud of?",
        "Where do you see yourself in 5 years - realistically and idealistically?",
        "What skill do you most want to master and why?",
        "What's currently on your bucket list that feels most important?",
        "What would you attempt if you knew you couldn't fail?",
        "What's your biggest goal that might sound crazy to others?",
        "What legacy do you want to create through your life's work?",
        "What fear is currently holding you back from a dream?",
        "How do you want to challenge yourself in the coming year?",
        "What does your ideal life look like 10 years from now?",
        "What's a goal you've achieved that once felt impossible?",
        "What dreams have you outgrown and what new ones have emerged?",
        "How do you want our relationship to support each other's dreams?",
        "What's something you want to learn or experience together?",
        "What impact do you want to have on the world?",
        "What's a risk you want to take for your personal growth?",
        "What dreams are you willing to sacrifice for, and which aren't worth it?"
    ],
    
    // Round 3 Categories (Deepest) - after Speed Categories
    'soul-connection': [
        "What do you believe your soul came here to learn in this lifetime?",
        "When do you feel most connected to something greater than yourself?",
        "What spiritual practice or belief system grounds you most?",
        "How has your capacity to love and be loved evolved over time?",
        "What does unconditional love mean to you in practice?",
        "When do you feel most aligned with your true purpose?",
        "What synchronicities or 'signs' have guided your path in life?",
        "How do you connect with your intuition and inner wisdom?",
        "What does soul-level intimacy feel like to you?",
        "How do you honor both your individual growth and our connection?",
        "What sacred rituals or practices do you want to cultivate?",
        "When do you feel most expansive and connected to life?",
        "What spiritual truth resonates most deeply with your heart?",
        "How do you find meaning and purpose in everyday moments?",
        "What does it mean to you to 'love someone's soul'?",
        "How do you want to continue growing spiritually together?",
        "What healing or transformation is your soul calling for now?",
        "When have you felt the presence of something divine or magical?",
        "What wisdom would your highest self share with others?",
        "How do you stay connected to love during difficult times?"
    ],
    
    'intimacy-passion': [
        "What makes you feel most desired and beautiful/handsome?",
        "How do you like to build anticipation and romantic tension?",
        "What kind of intimacy - physical, emotional, spiritual - do you crave most?",
        "When do you feel most vulnerable yet completely safe with someone?",
        "What's the difference between having sex and making love to you?",
        "How do you express desire and need without using words?",
        "What intimate moment between us has felt most sacred or transformative?",
        "When does time seem to stop during our intimate moments?",
        "What makes you feel most cherished and adored?",
        "How has physical intimacy healed or opened your heart?",
        "What fantasy or desire have you been curious about exploring?",
        "How do you want to keep discovering each other's bodies and desires?",
        "What boundary would you be interested in exploring together?",
        "When do you feel most powerful and confident in your sexuality?",
        "How do you want intimacy to evolve and deepen between us?",
        "What turns you on beyond the physical - intellectually, emotionally?",
        "How do you like to be touched when you're feeling emotional?",
        "What intimate ritual would you like to create together?",
        "How does emotional connection affect your physical desire?",
        "What makes you feel most sexually alive and awakened?"
    ],
    
    'lifes-big-questions': [
        "What life lesson took you the longest to learn and accept?",
        "How do you find meaning and purpose during your darkest times?",
        "What truth about life do you wish you had known much sooner?",
        "What wisdom would you want to pass on to future generations?",
        "How do you want to be remembered after you're gone?",
        "What questions about existence and meaning keep you awake at night?",
        "How do you make peace with life's uncertainty and impermanence?",
        "What gives your life the deepest sense of meaning and purpose?",
        "What would you tell your younger self about navigating life's challenges?",
        "How do you stay hopeful and positive during really difficult times?",
        "What do you think is the point of human suffering and struggle?",
        "How has your understanding of happiness and fulfillment evolved?",
        "What do you believe about fate, destiny, and free will?",
        "What fear about life or death do you still carry?",
        "How do you define what makes a life truly worth living?",
        "What illusion about life have you had to let go of?",
        "How do you cultivate gratitude when life feels overwhelming?",
        "What truth do you hold onto even when others disagree?",
        "How do you find beauty and joy in the midst of life's messiness?",
        "What questions about love, loss, and meaning matter most to you?"
    ]
};

// Function to get random questions from a category
function getRandomQuestions(category, count) {
    const categoryQuestions = questions[category];
    const shuffled = [...categoryQuestions].sort(() => 0.5 - Math.random());
    return shuffled.slice(0, count);
}